// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdvlzzuioijlqopuagcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhkdmx6enVpb2lqbHFvcHVhZ2N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNjAzOTgsImV4cCI6MjA1NTczNjM5OH0.Geh8Yo1l--F-cv9IuHdQ682C7EMZhIJDdaE7zdP6J9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);